notes_app/backend/notes_app/notes/urls.py
from django.urls import path

from .views import  delete_note, update_profile,AddTagView,UserProfileView ,CreateUserView, NoteListView, TagListView, UserLoginView, delete_tag, logout_user
from django.shortcuts import render, redirect

def dashboard(request):
    if not request.user.is_authenticated:
        return redirect('notes:login')
    return render(request, 'dashboard/notes.html')


app_name = 'notes'
urlpatterns = [
    path('signup/', CreateUserView.as_view(), name='signup'),
    path('login', UserLoginView.as_view(), name='login'),
    path('logout', logout_user, name='logout'),
    path('profile', UserProfileView.as_view(), name='profile' ),
    path('notes/', NoteListView.as_view(), name='notes'),
    path('notes/delete', delete_note, name='delete'),
    path('tags/', TagListView.as_view(), name='tags'),
    path('tags/add/', AddTagView.as_view(), name='tags-add'),
    path('tags/delete/<int:tag_id>/', delete_tag, name='tags-delete'),
]

notes_app/backend/notes_app/notes_app/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('notes.urls', namespace='notes')),
    path('api/v1/', include('notes.api.rest.urls')),
    path('api/v1/users/', include('dj_rest_auth.urls')),
    path('api/v1/users/registration/', include('dj_rest_auth.registration.urls')),
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/v1/docs/swagger', SpectacularSwaggerView.as_view(url_name="schema"), name='docs'),
    path('api/v1/docs/redoc', SpectacularRedocView.as_view(url_name="schema"), name='docs'),

]

notes_app/backend/notes_app/templates/dashboard/dashboard/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="{% static 'js/main.js' %}"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Foundation&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
        <title>{% block title %}{% endblock %}</title>
        <style>
            .onshow {
                width: 50%;
                box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;

            }

            .ss {
                box-shadow: rgba(0, 0, 0, 0.05) 0px 6px 24px 0px, rgba(0, 0, 0, 0.08) 0px 0px 0px 1px;
            }
        </style>
    </head>

    <body class="h-screen w-screen relative">
        {% include './modal.html' %}
        <main class="relative flex h-screen w-full">
            {% include './sidebar.html' %}
            <section class="basis-full md:basis-5/6 bg-slate-50 overflow-auto">
                {% include './searchbar.html' %}
                {% block content %}

                {% endblock %}
            </section>
        </main>
        <footer></footer>
        <script>
            window.onresize = () => {
                if (window.screen.width > 675) {
                    menu.classList.remove('onshow');
                }
            }
            window.onclick = () => {
                if (event.target.id != 'menu') {
                    const menu = document.getElementById('menu')
                    if (menu.classList.contains('onshow')) {
                        menu.classList.remove('onshow');
                    }
                }
            }

        </script>
    </body>

</html>

notes_app/backend/notes_app/templates/dashboard/dashboard/modal.html
<div id="add-modal" class="absolute hidden  z-10 items-center justify-center left-0 top-0 w-full h-screen  "
    style="background-color:#2228;">
    <div class="w-11/12 relative  md:w-1/2 rounded p-4  bg-white ss">
        <button onclick="hideModal();" class="absolute right-1 top-1 p-1">
            <i class="bi-x text-black text-xl"></i>
        </button>
        <form method="post" id="the-form" action="{% url 'notes:notes' %}" class="p-2 m-1 flex flex-col">
            {% csrf_token %}
            <input type="hidden" name="note_id" value="">
            <input name="title" placeholder="Title" type="text" class="p-1 outline-none text-lg text-gray-800 w-full">
            <textarea placeholder="Body..." name="body" id=""
                class="p-1 resize-none outline-none text-sm text-gray-600 w-full mt-2" cols="30" rows="5"></textarea>
            <section name="tags" class="mt-2 w-full p-2  text-sm font-extrabold text-gray-800 flex gap-1 flex-wrap">
                {% for tag in user.tags.all %}
                <label class="select-none cursor-pointer p-2">
                    <input type="checkbox" name="tags" value="{{tag.id}}" class="peer hidden"
                        {% if tag.name in selected_tags %}checked{% endif %}>
                    <span class="peer-checked:bg-sky-600 peer-checked:text-white p-2 rounded">{{tag.name}}</span>
                </label>
                {% endfor %}
            </section>

            <div class="flex justify-end gap-2 mt-2 p-1">
                <button id="delete-btn" formaction="{% url 'notes:delete' %}"
                    class="p-2 hidden text-white bg-red-500 px-4 rounded">Delete</button>
                <button class="p-2 text-white bg-sky-500 px-4 rounded">Add</button>
            </div>
        </form>
    </div>
</div>

notes_app/backend/notes_app/templates/dashboard/dashboard/searchbar.html
<nav class="h-16 shadow p-2 flex justify-between bg-white w-full"
    style="box-shadow: rgba(0, 0, 0, 0.1) 0px 20px 25px -5px, rgba(0, 0, 0, 0.04) 0px 10px 10px -5px;">
    <div class="flex gap-2 p-2 items-center group">
        <button onclick="toggleMenu();">
            <i class="bi-list text-2xl md:hidden text-gray-400"></i>
        </button>
        <form action="{% url 'notes:notes' %}" class="flex gap-1 text-lg items-center px-4">
            <i class="bi-search group-focus-within:text-gray-600 text-gray-400"></i>
            <input name="search" type="search" value="{% if search %}{{search}}{% endif %}"
                class="outline-none group-focus-within:text-gray-600 p-2 w-full text-gray-500" placeholder="Search...">
        </form>
    </div>
    <div class="flex gap-6 items-center px-3">
        <div class="flex gap-2 items-center">
            <div class="w-8 h-8 md:h-10 md:w-10 rounded-full border border-gray-400">
                <img src="https://i.pravatar.cc/300" class="object-cover rounded-full" alt="">
            </div>
            <h6 class="text-gray-500 text-sm md:text-lg">{{user.username}}</h6>
        </div>
        <button class="relative">
            <i class="bi-bell text-gray-500 text-xl md:text-2xl"></i>
            <span class="h-2 w-2 rounded-full bg-red-500 absolute top-0 left-0.5"></span>
        </button>
    </div>
</nav>

notes_app/backend/notes_app/templates/dashboard/dashboard/sidebar.html
<section id="menu"
    class="absolute w-0 transition-all overflow-hidden h-screen top-0 left-0 md:relative  flex md:basis-1/6 bg-sky-600  flex-col justify-between gap-2">
    <button class="md:hidden cursor-pointer" onclick="toggleMenu();">
        <i class="bi-x text-white absolute right-1 top-1 text-2xl"></i>
    </button>
    <h1 class="p-4 hidden md:block text-center text-white bg-gray-700 text-2xl">NOTES</h1>
    <ul class="flex flex-col w-full p-8 text-white font-extrabold text-lg gap-2">
        <li>
            <a class="p-1 flex gap-2" href="{% url 'notes:notes' %}">
                <i class="bi-table"></i>
                <span>Notes</span>
            </a>
        </li>

        <li>
            <a class="p-1 flex gap-2" href="{% url 'notes:tags' %}">
                <i class="bi-tags-fill"></i>
                <span>Tags</span>
            </a>
        </li>
        <li>
            <a class="p-1 flex gap-2" href="#">
                <i class="bi-stopwatch-fill"></i>
                <span>Events</span>
            </a>
        </li>

        <li>
            <a class="p-1 flex gap-2" href="{% url 'notes:profile' %}">
                <i class="bi-person-fill"></i>
                <span>Profile</span>
            </a>
        </li>
        <li>
            <a class="p-1 flex gap-2" href="{% url 'notes:logout' %}">
                <i class="bi-x-circle-fill"></i>
                <span>Logout</span>
            </a>
        </li>

    </ul>
    <ul class="p-2 flex justify-center items-center gap-4 text-white text-lg">
        <i class="bi-facebook"></i>
        <i class="bi-twitter"></i>
        <i class="bi-github"></i>
        <i class="bi-google"></i>
    </ul>
</section>