notes_app/backend/notes_app/notes/api/rest/urls.py
from email.mime import base
from rest_framework.routers import DefaultRouter

from .views import NoteViewset, TagViewset

router = DefaultRouter()
router.register(r'notes',NoteViewset, basename='notes')
router.register(r'tags', TagViewset, basename='tags')

urlpatterns = router.urls

notes_app/backend/notes_app/notes/urls.py
from django.urls import path

from .views import  delete_note, update_profile,AddTagView,UserProfileView ,CreateUserView, NoteListView, TagListView, UserLoginView, delete_tag, logout_user
from django.shortcuts import render, redirect

def dashboard(request):
    if not request.user.is_authenticated:
        return redirect('notes:login')
    return render(request, 'dashboard/notes.html')


app_name = 'notes'
urlpatterns = [
    path('signup/', CreateUserView.as_view(), name='signup'),
    path('login', UserLoginView.as_view(), name='login'),
    path('logout', logout_user, name='logout'),
    path('profile', UserProfileView.as_view(), name='profile' ),
    path('notes/', NoteListView.as_view(), name='notes'),
    path('notes/delete', delete_note, name='delete'),
    path('tags/', TagListView.as_view(), name='tags'),
    path('tags/add/', AddTagView.as_view(), name='tags-add'),
    path('tags/delete/<int:tag_id>/', delete_tag, name='tags-delete'),
]

notes_app/backend/notes_app/notes_app/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('notes.urls', namespace='notes')),
    path('api/v1/', include('notes.api.rest.urls')),
    path('api/v1/users/', include('dj_rest_auth.urls')),
    path('api/v1/users/registration/', include('dj_rest_auth.registration.urls')),
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/v1/docs/swagger', SpectacularSwaggerView.as_view(url_name="schema"), name='docs'),
    path('api/v1/docs/redoc', SpectacularRedocView.as_view(url_name="schema"), name='docs'),

]

notes_app/backend/notes_app/notes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

AUTH_USER = get_user_model()

class Tag(models.Model):
    user = models.ForeignKey(to=User, related_name='tags', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, unique=True, db_index=True)
    class Meta:
        unique_together = ('user', 'name')

    
    def __str__(self) -> str:
        return self.name
    
class Note(models.Model):
    user = models.ForeignKey(to=User, related_name='notes', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(to=Tag, related_name='notes')
    due_date = models.DateTimeField(null=True, blank=True)

    def __str__(self) -> str:
        return  self.title
    




                                  

notes_app/backend/notes_app/notes/forms.py
from dataclasses import field, fields
from django import forms
from .models import Note, Tag
from django.contrib.auth.models import User



class AddTagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ('name', )
    

class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class AddNoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('title', 'body', 'tags')

notes_app/backend/notes_app/notes/api/rest/views.py
from notes.models import *
from .serializers import NoteSerializer, TagSerializer
from rest_framework import viewsets
from rest_framework import permissions
from django_filters.rest_framework.backends import DjangoFilterBackend
from rest_framework import exceptions

from .permissions import IsOwner

class TagViewset(viewsets.ModelViewSet):
    serializer_class = TagSerializer
    permission_classes = [permissions.IsAuthenticated, IsOwner]
    
    def get_queryset(self):
        return Tag.objects.filter(user=self.request.user)
    
    def perform_create(self, serializer):
        serializer.save(user=self.request.user)
        
    
class NoteViewset(viewsets.ModelViewSet):
    serializer_class = NoteSerializer
    permission_classes = [permissions.IsAuthenticated, IsOwner]
    filter_backends = (DjangoFilterBackend, )
    filterset_fields = ('tags__name', )
    
    def get_queryset(self):
        return Note.objects.filter(user=self.request.user)
    
    def perform_create(self, serializer):
        tags = serializer.validated_data.get('tags')
        # Only user's added tags allowed...
        for tag in tags:
            if tag.user != self.request.user:
                raise exceptions.NotAcceptable('you dont have such tags...')
        serializer.save(user=self.request.user)

notes_app/backend/notes_app/notes/views.py
from ast import FormattedValue
from asyncio.format_helpers import _format_callback_source
from locale import format_string
from urllib import request
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpRequest
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.generic import CreateView, ListView, DeleteView, FormView, UpdateView
from django.db.models import Q
from django.urls import reverse_lazy
from typing import *
from django.http import HttpResponseNotAllowed
from .forms import AddNoteForm, AddTagForm, UpdateUserForm
from .models import *


AUTH_USER = get_user_model()


class CreateUserView(FormView):
    form_class = UserCreationForm
    template_name: str = 'users/signup.html'

    def form_valid(self, form) -> HttpResponse:
        form.save()
        return redirect('notes:notes')
    
    def dispatch(self, request: HttpRequest, *args: Any, **kwargs: Any):
        if request.user.is_authenticated:
            return redirect('notes:notes')
        
        return super().dispatch(request, *args, **kwargs)
    

class UserLoginView(LoginView):
    template_name: str = 'users/login.html'
    success_url: Optional[str] =  reverse_lazy('notes:notes')
    next_page = reverse_lazy('notes:notes')
    redirect_authenticated_user: bool = True


def logout_user(request: HttpResponse):
    logout(request)
    return redirect('notes:login')


class NoteListView(ListView,FormView, LoginRequiredMixin):
    model = Note
    template_name: str = 'dashboard/notes.html'
    paginate_by: int = 20
    context_object_name: Optional[str] = 'notes'
    form_class = AddNoteForm
    
    def form_valid(self, form) -> HttpResponse:
        print(form.cleaned_data)
        note_id = self.request.POST.get('note_id')
        if note_id:
            note = get_object_or_404(Note, user=self.request.user, pk=note_id)
            form.instance = note
        
        note = form.save(commit=False)
        note.user = self.request.user
        note.save()
        form.save_m2m()
        return redirect('notes:notes')
    
    def form_invalid(self, form) -> HttpResponse:
        return HttpResponse(form.errors)
    
    def get_queryset(self):
        tags = self.request.GET.getlist('tags')
        search_keywords = self.request.GET.get('search')
        notes = Note.objects.filter(user=self.request.user)
        if tags:
            notes &= Note.objects.filter(tags__name__in=tags)
        if search_keywords:
            print(search_keywords)
            notes &= Note.objects.filter(Q(tags__name__icontains=search_keywords) 
                                  | Q(title__icontains=search_keywords) 
                                  | Q(body__icontains=search_keywords))
        return notes
    


    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        data = super().get_context_data(**kwargs)
        data['selected_tags'] = self.request.GET.getlist('tags')
        data['search'] = self.request.GET.get('search')
        return data



@login_required
def delete_note(request: HttpRequest):
    note_id = request.POST.get('note_id')
    note = get_object_or_404(Note, pk=note_id, user=request.user)
    note.delete()
    return redirect('notes:notes')


class TagListView(ListView, LoginRequiredMixin):
    model = Tag
    template_name: str = 'dashboard/tags.html'
    context_object_name: Optional[str] = 'tags'
    
    def get_queryset(self):
        return Tag.objects.filter(user=self.request.user)


@login_required
def delete_tag(request: HttpRequest, tag_id):
    tag = get_object_or_404(Tag, pk=tag_id, user=request.user)
    tag.delete()
    return redirect('notes:tags')


class AddTagView(FormView):
    model = Tag
    fields = ('name', )
    form_class = AddTagForm
    
    def form_valid(self, form) -> HttpResponse:
        tag = form.save(commit=False)
        tag.user = self.request.user
        tag.save()
        return redirect('notes:tags')

    
#------------------------- wHIH IS BETTER ?-------------------
class UserProfileView(FormView, LoginRequiredMixin):
    template_name = 'dashboard/profile.html'
    form_class = UpdateUserForm
    success_url = reverse_lazy('notes:profile')

    def get_form_kwargs(self) -> Dict[str, Any]:
        kwrags = super().get_form_kwargs()
        kwrags.update({'instance': self.request.user})
        return kwrags
    
    def form_valid(self, form) -> HttpResponse:
        form.save()
        return render(self.request,'dashboard/profile.html')
    

@login_required
def update_profile(request: HttpRequest):
    context = None
    if request.method == 'POST':
        form = UpdateUserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            
        context =  {
            'status': 'updated'
        }
    return render(request, 'dashboard/profile.html', context)

class PasswordChangeView(FormView):
    form_class = PasswordChangeForm
    template_name: str = 'dashboard/profile.html'
    success_url: Optional[str] = 'dashboard/profile.html'
    
    

notes_app/backend/notes_app/templates/dashboard/note.html
<article onclick="editNote();" data-noteid="{{note.id}}"
    class="ss cursor-pointer  flex flex-col p-4 basis-1/4 bg-white rounded-sm shadow">
    <span class="text-gray-400 text-xs">{{note.date_created}}</span>
    <h4 id="ss1" name="title" aria-label="title" class="text-gray-600 mt-2">{{note.title}}</h4>
    <p name="body" aria-label="body" class="text-xs text-gray-400 mt-4  ">
        {{note.body}}
    </p>
    <div name="tags" aria-label="tags" class="flex gap-1 text-gray-500 text-[0.6rem] mt-4 flex-wrap">
        {% for tag in note.tags.all %}
        <span data-tagid="{{tag.id}}" class="rounded-sm p-1 bg-gray-700 text-white">{{tag.name}}</span>
        {% endfor %}
    </div>
</article>

notes_app/backend/notes_app/templates/dashboard/notes.html
{% extends './dashboard/dashboard.html' %}
{% load static %}


{% block title %}Notes{% endblock %}


{% block content %}

<template id="add-edit-note">

</template>

<section class="flex justify-end mt-4">
    <button onclick="showModal();" class="flex gap-1 m-4 p-2 hover:bg-slate-100 rounded items-center">
        <i class="bi-plus text-4xl text-green-600"></i>
        <span class="text-xl text-gray-600">Add a Note</span>
    </button>
</section>
<form class="w-full flex-col gap-2">
    <section class="mt-12 w-11/12 p-2  text-sm font-extrabold text-gray-800 flex gap-1 flex-wrap mx-auto">
        {% for tag in user.tags.all %}
        <label class="select-none cursor-pointer p-2">
            <input type="checkbox" name="tags" value="{{tag.name}}" class="peer hidden"
                {% if tag.name in selected_tags %}checked{% endif %}>
            <span class="peer-checked:bg-sky-600 peer-checked:text-white p-2 rounded">{{tag.name}}</span>
        </label>
        {% endfor %}
    </section>
    <div class="flex p-4 mt-2 justify-end">
        <button type="submit" class="p-2 text-white rounded shadow text-sm px-4 bg-gray-600">Apply tags</button>
    </div>
</form>
<section class="mt-8 gap-2  p-4 grid grid-cols-1 md:grid-cols-4 flex-wrap w-full">
    {% for note in notes %}
    {% include './note.html' %}
    {% endfor %}
</section>
{% endblock %}

notes_app/backend/notes_app/templates/dashboard/profile.html
{% extends './dashboard/dashboard.html' %}
{% load static %}


{% block title %}Notes{% endblock %}


{% block content %}

<section class="w-full  flex items-center flex-col  mt-4 h-full">
    <form method="post" action="{% url 'notes:profile' %}"
        class="p-6 text-gray-600 ss rounded-md  bg-white flex flex-col gap-4 m-4">
        {% csrf_token %}
        <label class="flex flex-col gap-1">
            <span>Fisrt name:</span>
            <input type="text" value="{{user.first_name}}"
                class="p-2 rounded-md border focus:border-gray-500 outline-none" name="first_name" id="">
        </label>
        <label class="flex flex-col gap-1">
            <span>Last name:</span>
            <input type="text" value="{{user.last_name}}"
                class="p-2 rounded-md border focus:border-gray-500 outline-none" name="last_name" id="">
        </label>

        <label class="flex flex-col gap-1">
            <span>Email:</span>
            <input type="email" value="{{user.email}}" class="p-2 rounded-md border focus:border-gray-500 outline-none"
                name="email" id="">
        </label>
        <label class="flex flex-col gap-1">
            <span>Avatar:</span>
            <input type="file" class="p-2 rounded-md border focus:border-gray-500 outline-none" name="" id="">
        </label>
        <button type="submit" class="bg-sky-600 text-white p-2 rounded"
            style="box-shadow: rgba(0, 0, 0, 0.1) 0px 4px 12px;">Save</button>

    </form>
    <form method="post" action="" class="p-6 -mt-1 text-gray-600 ss rounded-md  bg-white flex flex-col gap-4 m-4">
        <label class="flex flex-col gap-1">
            <span>New password:</span>
            <input autocomplete="new-password" type="password"
                class="p-2 rounded-md border focus:border-gray-500 outline-none" name="password1" id="">
        </label>
        <label class="flex flex-col gap-1">
            <span>Confirm:</span>
            <input type="password" autocomplete="new-password"
                class="p-2 rounded-md border focus:border-gray-500 outline-none" name="password2" id="">
        </label>
        <button class="bg-red-600 text-white p-2 rounded"
            style="box-shadow: rgba(0, 0, 0, 0.1) 0px 4px 12px;">Reset</button>
    </form>
    <section class="mt-4 p-2"></section>
</section>
</section>
{% endblock %}

notes_app/backend/notes_app/templates/dashboard/tags.html
{% extends './dashboard/dashboard.html' %}
{% load static %}

{% block title %}Tags{% endblock %}


{% block content %}
<section class="w-full p-4 mt-16">
    <form action="{% url 'notes:tags-add' %}" method="post" class="w-11/12 md:w-1/2 flex flex-col mx-auto rounded">
        {% csrf_token %}
        <input name="name" autofocus placeholder="Tag name" type="text"
            class="p-3 text-gray-500 bg-white outline-none ss rounded">
        <div class="flex mt-3  justify-end">
            <button type="submit" class="bg-sky-600 shadow p-2 text-white px-4 rounded">Add</button>
        </div>
    </form>
    <div class="w-11/12 md:w-3/4 mx-auto mt-16 text-gray-700 text-sm p-2 flex gap-2 flex-wrap">
        {% for tag in tags %}
        <div class="p-2 rounded-md flex items-center gap-2 w-fit bg-slate-100">
            <span>{{ tag.name }}</span>
            <a href="{% url 'notes:tags-delete' tag.id %}"><i class="bi-x text-lg"></i></a>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock %}