notes_app/backend/notes_app/notes/urls.py
from django.urls import path

from .views import  delete_note, update_profile,AddTagView,UserProfileView ,CreateUserView, NoteListView, TagListView, UserLoginView, delete_tag, logout_user
from django.shortcuts import render, redirect

def dashboard(request):
    if not request.user.is_authenticated:
        return redirect('notes:login')
    return render(request, 'dashboard/notes.html')


app_name = 'notes'
urlpatterns = [
    path('signup/', CreateUserView.as_view(), name='signup'),
    path('login', UserLoginView.as_view(), name='login'),
    path('logout', logout_user, name='logout'),
    path('profile', UserProfileView.as_view(), name='profile' ),
    path('notes/', NoteListView.as_view(), name='notes'),
    path('notes/delete', delete_note, name='delete'),
    path('tags/', TagListView.as_view(), name='tags'),
    path('tags/add/', AddTagView.as_view(), name='tags-add'),
    path('tags/delete/<int:tag_id>/', delete_tag, name='tags-delete'),
]

notes_app/backend/notes_app/notes_app/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('notes.urls', namespace='notes')),
    path('api/v1/', include('notes.api.rest.urls')),
    path('api/v1/users/', include('dj_rest_auth.urls')),
    path('api/v1/users/registration/', include('dj_rest_auth.registration.urls')),
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/v1/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/v1/docs/swagger', SpectacularSwaggerView.as_view(url_name="schema"), name='docs'),
    path('api/v1/docs/redoc', SpectacularRedocView.as_view(url_name="schema"), name='docs'),

]

notes_app/backend/notes_app/templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Foundation&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

        <style>
            .ss {
                box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
            }
        </style>
        <title>Login</title>
    </head>

    <body class="w-full relative h-screen bg-slate-50">
        <main class="flex justify-center h-screen p-4 items-center ">
            <form method="post" action="{% url 'notes:login' %}"
                class="p-6 text-gray-600 ss rounded-md  bg-white flex flex-col gap-4 m-4">
                {% csrf_token %}
                <label class="flex flex-col gap-1">
                    <span>Username:</span>
                    <input name="username" type="text" class="p-2 rounded-md border focus:border-gray-500 outline-none"
                        name="" id="">
                </label>
                <label class="flex flex-col gap-1">
                    <span>Password:</span>
                    <input type="password" name="password"
                        class="p-2 rounded-md border focus:border-gray-500 outline-none" name="" id="">
                </label>
                <button type="submit" class="bg-sky-600 text-white p-2 rounded"
                    style="box-shadow: rgba(0, 0, 0, 0.1) 0px 4px 12px;">Login</button>
                <a href="{% url 'notes:signup' %}"
                    class="bg-gray-700 -mt-1 text-white p-2 text-center rounded">Singup</a>
            </form>
        </main>
        <footer
            class="bg-slate-200 w-full p-1 text-gray-500 flex gap-2 justify-center items-center absolute bottom-0 left-0">
            summer 2022 by 0x-m<i class="bi-github text-lg"></i>
        </footer>
    </body>

</html>

notes_app/backend/notes_app/templates/users/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Foundation&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

        <style>
            .ss {
                box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
            }
        </style>
        <title>Signup</title>
    </head>

    <body class="w-full relative h-screen bg-slate-50">
        <main class="flex justify-center h-screen p-4 items-center ">
            <form method="post" action="{% url 'notes:signup' %}"
                class="p-6 text-gray-600 ss rounded-md  bg-white flex flex-col gap-4 m-4">
                {% csrf_token %}
                <label class="flex flex-col gap-1">
                    <span>Username:</span>
                    <input required type="text" name="username"
                        class="p-2 rounded-md border focus:border-gray-500 outline-none" name="" id="">
                </label>
                <!-- <label class="flex flex-col gap-1">
                    <span>Email:</span>
                    <input type="email" class="p-2 rounded-md border focus:border-gray-500 outline-none" name="" id="">
                </label> -->
                <label class="flex flex-col gap-1">
                    <span>Password:</span>
                    <input required type="password" name="password1" autocomplete="new-password"
                        class="p-2 rounded-md border focus:border-gray-500 outline-none" name="" id="">
                </label>
                <label class="flex flex-col gap-1">
                    <span>Password Confirmation:</span>
                    <input required type="password" name="password2" autocomplete="new-password"
                        class="p-2 rounded-md border focus:border-gray-500 outline-none" name="" id="">
                </label>

                <button class="bg-sky-600 text-white p-2 rounded" type="submit"
                    style="box-shadow: rgba(0, 0, 0, 0.1) 0px 4px 12px;">Signup</button>
                <div class="flex gap-2 justify-center items-center text-gray-400">
                    <a href="#">
                        <i class="bi-facebook hover:text-gray-700"></i>
                    </a>
                    <a href="#">
                        <i class="bi-twitter  hover:text-gray-700"></i>
                    </a>
                    <a href="#">
                        <i class="bi-google  hover:text-gray-700"></i>
                    </a>
                </div>
                {{form.errors}}
            </form>
        </main>
        <footer
            class="bg-slate-200 w-full p-1 text-gray-500 flex gap-2 justify-center items-center absolute bottom-0 left-0">
            summer 2022 by 0x-m<i class="bi-github text-lg"></i>
        </footer>
    </body>

</html>